### PR TITLE
cart: add event that is dispatched before an order is placed

### PR DESCRIPTION
**Pull request by carstendietrich**
Currently we only have an event after the order is placed. Maybe I want to check / do stuff right before the order is placed.

### CODE REVIEW

**Comment by danielpoe** [comment]
What would be a concrete use case?
Why not add a payload to the event?

**Comment by carstendietrich** [comment]
Concrete use case would be adding additional attributes to the cart before placing it. There are hooks for that, but they only get triggered on certain cart actions which make it hard to ensure correct attributes if they depend on the cart content. The event doesn't really need additional payload since you can fetch the cart from the context and update it.

**Comment by danielpoe** [comment]
I think an event should be self contained - telling a bit about the ressource where it appeared.
(fetching the cart via sie effect might in theory give you something else in a concurrent system)

But still expecting the event to trigger via side effect a change on the cart that will be placed some lines after the event is triggered feels strange.

Events are meant for listing and not for changing something on the ressource via sideeffect

Currently we have a Hook for adding attributes directly in the Adapter>Mapper of flamingo_om3 - Maybe we can either:
- use simelar hook in the Adapter where we need it..
- or add an explicit Hook in flamingo_commerce if we think that should be a common behaviour that "someone" should modify the cart just before it is placed..

**Comment by carstendietrich** [comment]
Jeah thats sounds reasonable I guess my solution was kinda rushed. Im closing this PR for now and come up with a better solution.

**Pull request closed without merging**
