### PR TITLE
Allow filters with multiple values

### PR DESCRIPTION
**Pull request by dylan-provost**
Refactor the FindProducts function

### CODE REVIEW

**Comment by dylan-provost** [comment]
> Please also update the Readme with an example

Since there is nothing new it was just a fix and a refactoring, I just fixed the typos in the Readme

**Comment by danielpoe** [comment]
> > Please also update the Readme with an example
> 
> Since there is nothing new it was just a fix and a refactoring, I just fixed the typos in the Readme

The title is saying "Allow filters with multiple values" - so I it sounds like an extended feature??

**Comment by dylan-provost** [comment]
> > > Please also update the Readme with an example
> > 
> > 
> > Since there is nothing new it was just a fix and a refactoring, I just fixed the typos in the Readme
> 
> The title is saying "Allow filters with multiple values" - so I it sounds like an extended feature??

I think the first implementation just completely missed that point in the first place. URLs can obviously contain multiple filters, and we should be able to filter all of them, that is why the filters are documented as an map of strings. But I don't know what the Readme should say more than it says right now. Any idea?

**Comment by danielpoe** [comment]
> > > > Please also update the Readme with an example
> > > 
> > > 
> > > Since there is nothing new it was just a fix and a refactoring, I just fixed the typos in the Readme
> > 
> > 
> > The title is saying "Allow filters with multiple values" - so I it sounds like an extended feature??
> 
> I think the first implementation just completely missed that point in the first place. URLs can obviously contain multiple filters, and we should be able to filter all of them, that is why the filters are documented as an map of strings. But I don't know what the Readme should say more than it says right now. Any idea?

Ok then I misuderstood the title. Thanks for clarification

**Pull request merged**
