### PR TITLE
search: extend suggestions with type and additional attributes

### PR DESCRIPTION
**Pull request by tlayh**
Adding CategorySuggestions

### CODE REVIEW

**Comment by tlayh** [comment]
> 1. Please add a Changelog.md to the search module (for an example have a look at the cart module) mentioning the new struct field.
> 2. Please add the new field also to the `SearchResult` struct of the `application/searchService` and map it correctly in the `Find` and `FindBy` methods

Added the required changes.

**Comment by danielpoe** [comment]
Looks a bit specific - not sure if this is worth adding new types to commerce core?
Can Suggestion be used in the way how Documents are used (specific types are up to the using module)

**Comment by tlayh** [comment]
> Looks a bit specific - not sure if this is worth adding new types to commerce core?
> Can Suggestion be used in the way how Documents are used (specific types are up to the using module)

I think other projects could benefit from category suggestions as well. Do you have any good idea how to do this different on a project specific level?

**Comment by carstendietrich** [comment]
@tlayh as talked:

please remove the new struct and add a `Type string` and `AdditionalAttributes map[string]string` to the existing `Suggestion` struct. Add also consts for Suggestion Type Product and Suggestion Type Category. Maybe we also add brands right away.

**Pull request merged**
