### PR TITLE
sourcing: Add deliveryInfo to interface StockProvider GetStock

### PR DESCRIPTION
**Pull request by masmrlar**
Implementing StockProviders require the deliveryInfo for specific stock checks.

### CODE REVIEW

**Comment by danielpoe** [comment]
Can you give details for the use case?

**Comment by masmrlar** [comment]
@danielpoe a usecase for this is for example a requirement where the StockProvider has to use a specific logic based on product data/attributes and the deliveryInfo (like DeliveryCode) - to override stock data. 

And a pretty specific usecase is: we want to have a delivery specific alwaysInStock logic - let's call it `alwaysInStockForDelivery` beneath `alwaysInStock`.

**Review by carstendietrich — CHANGES_REQUESTED** [review]
I guess it can't hurt that the stock also gets the delivery info, never the less it's a breaking change. Please, update the project's main CHANGELOG.md and mark this change as breaking.

**Review by carstendietrich — APPROVED** [review]
Looks fine.

**Pull request merged**
